require:
  - rubocop-faker
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Lint/MissingCopEnableDirective:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

RSpec/Capybara/FeatureMethods:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
