require:
  - rubocop-faker
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Metrics/BlockLength:
  Enabled: false

RSpec/Capybara/FeatureMethods:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
