# Available properties ('+' means required):
#   + type (direct/git)
#   + version
#   + source (url)
#   ? checksum (required for direct)
#   - executable (or filename)
#   - visibility (public/private, default private)

cs-checkstyle:
  type: git
  version: 16
  source: https://github.ncsu.edu/engr-csc116-staff/cs-checkstyle.git
  executable: checkstyle

junit:
  type: direct
  version: 1.6.2
  source: https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.6.2/junit-platform-console-standalone-1.6.2.jar
  checksum: 0
  visibility: public
