# Downloading path
root: vendor/dependencies

# Available properties: version, source, source_type, executable
cs-checkstyle:
  version: 16
  source: https://github.ncsu.edu/engr-csc116-staff/cs-checkstyle.git
  source_type: git
  executable: checkstyle

junit:
  version: 1.6.2
  source: https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.6.2/junit-platform-console-standalone-1.6.2.jar
  source_type: direct
  visibility: public
